# Generated by Django 5.0.4 on 2024-06-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.FileField(upload_to='files/a12b33d'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='files_count',
            field=models.IntegerField(default=0),
        ),
    ]
