# Generated by Django 5.0.4 on 2024-06-12 20:52

import django.utils.timezone
import storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_file_content_alter_folder_files_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.FileField(upload_to=storage.models.File.generate_filename),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=storage.models.generate_uuid, editable=False, primary_key=True, serialize=False),
        ),
    ]
