# Generated by Django 5.0.4 on 2024-06-23 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_folder_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['name']},
        ),
    ]
